# This rule is not used by the project fstackd-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to cache.gidraff.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: fstackd-operator
    app.kubernetes.io/managed-by: kustomize
  name: fstack-viewer-role
rules:
- apiGroups:
  - cache.gidraff.com
  resources:
  - fstacks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.gidraff.com
  resources:
  - fstacks/status
  verbs:
  - get
